package com.example.isa2017.model;

public enum MessageType {
	USPESNA_REZERVACIJA, USPESNA_REZERVACIJA_PROIZVODA, PRIHVACENA_PONUDA,ODOBREN_OGLAS,ODBIJEN_OGLAS, ODBIJENA_PONUDA, USKORO_ISTICE
}
